public class BILL {
   
    public static void main(String[] args) 
        {  
    
         // Print header
        System.out.printf("%-20s %10s %10s %10s %10s%n", "Product", "Quantity", "Price","Text","Total");
    
        // Print data in columnsfor (int i = 0; i < names.length; i++) {
            
        System.out.printf("%-20s %10d %10.2f %10s %10.2f%n", "i-phone", 1,42000.00,"18%" ,49560.00);
    }
}

